[versions]
agp = "8.6.0"
kotlin = "1.9.0"
material = "1.12.0"
playServicesWearable = "18.2.0"
appcompat = "1.7.0"
constraintlayout = "2.1.4"

[libraries]
material = { module = "com.google.android.material:material", version.ref = "material" }
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

